//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activities()
        {
            this.notification_recipients = new HashSet<notification_recipients>();
        }
    
        public long id { get; set; }
        public long user_id { get; set; }
        public string action_type { get; set; }
        public long target_id { get; set; }
        public string target_type { get; set; }
        public string content { get; set; }
        public System.DateTime created_at { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification_recipients> notification_recipients { get; set; }
    }
}
