//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachments
    {
        public long id { get; set; }
        public long uploaded_by_user_id { get; set; }
        public long attachable_id { get; set; }
        public string attachable_type { get; set; }
        public string original_filename { get; set; }
        public string storage_path { get; set; }
        public string file_type { get; set; }
        public Nullable<long> file_size { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
