//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string content { get; set; }
        public long commentable_id { get; set; }
        public string commentable_type { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
