//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitations
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public long inviter_id { get; set; }
        public string invitee_email { get; set; }
        public string token { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> expires_at { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
