//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_recipients
    {
        public long activity_id { get; set; }
        public long user_id { get; set; }
        public bool is_read { get; set; }
    
        public virtual activities activities { get; set; }
        public virtual users users { get; set; }
    }
}
