//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_members
    {
        public long project_id { get; set; }
        public long user_id { get; set; }
        public string role { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
