//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PronaFlow_DBContext : DbContext
    {
        public PronaFlow_DBContext()
            : base("name=PronaFlow_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<attachments> attachments { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<invitations> invitations { get; set; }
        public virtual DbSet<notification_recipients> notification_recipients { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
        public virtual DbSet<project_members> project_members { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<subtasks> subtasks { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<user_preferences> user_preferences { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<workspaces> workspaces { get; set; }
        public virtual DbSet<task_lists> task_lists { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<sp_GetProjectDetails_Result> sp_GetProjectDetails(Nullable<long> projectID, Nullable<long> userID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProjectDetails_Result>("sp_GetProjectDetails", projectIDParameter, userIDParameter);
        }
    
        public virtual int sp_MoveTask(Nullable<long> taskID, Nullable<long> newTaskListID)
        {
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(long));
    
            var newTaskListIDParameter = newTaskListID.HasValue ?
                new ObjectParameter("NewTaskListID", newTaskListID) :
                new ObjectParameter("NewTaskListID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MoveTask", taskIDParameter, newTaskListIDParameter);
        }
    
        public virtual ObjectResult<sp_SearchUsersForProject_Result> sp_SearchUsersForProject(Nullable<long> workspaceID, Nullable<long> projectID, string searchTerm)
        {
            var workspaceIDParameter = workspaceID.HasValue ?
                new ObjectParameter("WorkspaceID", workspaceID) :
                new ObjectParameter("WorkspaceID", typeof(long));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(long));
    
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchUsersForProject_Result>("sp_SearchUsersForProject", workspaceIDParameter, projectIDParameter, searchTermParameter);
        }
    
        public virtual int sp_DuplicateProject(Nullable<long> sourceProjectID, Nullable<long> userID)
        {
            var sourceProjectIDParameter = sourceProjectID.HasValue ?
                new ObjectParameter("SourceProjectID", sourceProjectID) :
                new ObjectParameter("SourceProjectID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DuplicateProject", sourceProjectIDParameter, userIDParameter);
        }
    
        public virtual int sp_GetProjectsForKanban(Nullable<long> workspaceID, Nullable<long> userID)
        {
            var workspaceIDParameter = workspaceID.HasValue ?
                new ObjectParameter("WorkspaceID", workspaceID) :
                new ObjectParameter("WorkspaceID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetProjectsForKanban", workspaceIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUserDashboardMetrics_Result> sp_GetUserDashboardMetrics(Nullable<long> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUserDashboardMetrics_Result>("sp_GetUserDashboardMetrics", userIDParameter);
        }
    
        public virtual int sp_GetUserTasks(Nullable<long> userID, Nullable<long> workspaceID, string searchTerm, string filterByProjectIDs, string filterByStatus, string sortBy)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var workspaceIDParameter = workspaceID.HasValue ?
                new ObjectParameter("WorkspaceID", workspaceID) :
                new ObjectParameter("WorkspaceID", typeof(long));
    
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var filterByProjectIDsParameter = filterByProjectIDs != null ?
                new ObjectParameter("FilterByProjectIDs", filterByProjectIDs) :
                new ObjectParameter("FilterByProjectIDs", typeof(string));
    
            var filterByStatusParameter = filterByStatus != null ?
                new ObjectParameter("FilterByStatus", filterByStatus) :
                new ObjectParameter("FilterByStatus", typeof(string));
    
            var sortByParameter = sortBy != null ?
                new ObjectParameter("SortBy", sortBy) :
                new ObjectParameter("SortBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetUserTasks", userIDParameter, workspaceIDParameter, searchTermParameter, filterByProjectIDsParameter, filterByStatusParameter, sortByParameter);
        }
    
        public virtual int sp_LogActivity(Nullable<long> userID, string actionType, Nullable<long> targetID, string targetType, string content)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var actionTypeParameter = actionType != null ?
                new ObjectParameter("ActionType", actionType) :
                new ObjectParameter("ActionType", typeof(string));
    
            var targetIDParameter = targetID.HasValue ?
                new ObjectParameter("TargetID", targetID) :
                new ObjectParameter("TargetID", typeof(long));
    
            var targetTypeParameter = targetType != null ?
                new ObjectParameter("TargetType", targetType) :
                new ObjectParameter("TargetType", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LogActivity", userIDParameter, actionTypeParameter, targetIDParameter, targetTypeParameter, contentParameter);
        }
    
        public virtual int sp_SoftDeleteUser(Nullable<long> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SoftDeleteUser", userIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
