//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PronaFlow_DBContext : DbContext
    {
        public PronaFlow_DBContext()
            : base("name=PronaFlow_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<attachments> attachments { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<invitations> invitations { get; set; }
        public virtual DbSet<notification_recipients> notification_recipients { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
        public virtual DbSet<project_members> project_members { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<subtasks> subtasks { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<task_lists> task_lists { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<user_preferences> user_preferences { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<workspaces> workspaces { get; set; }
    
        public virtual ObjectResult<sp_GetProjectDetails_Result> sp_GetProjectDetails(Nullable<long> projectID, Nullable<long> userID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProjectDetails_Result>("sp_GetProjectDetails", projectIDParameter, userIDParameter);
        }
    
        public virtual int sp_MoveTask(Nullable<long> taskID, Nullable<long> newTaskListID)
        {
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(long));
    
            var newTaskListIDParameter = newTaskListID.HasValue ?
                new ObjectParameter("NewTaskListID", newTaskListID) :
                new ObjectParameter("NewTaskListID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MoveTask", taskIDParameter, newTaskListIDParameter);
        }
    
        public virtual ObjectResult<sp_SearchUsersForProject_Result> sp_SearchUsersForProject(Nullable<long> workspaceID, Nullable<long> projectID, string searchTerm)
        {
            var workspaceIDParameter = workspaceID.HasValue ?
                new ObjectParameter("WorkspaceID", workspaceID) :
                new ObjectParameter("WorkspaceID", typeof(long));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(long));
    
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchUsersForProject_Result>("sp_SearchUsersForProject", workspaceIDParameter, projectIDParameter, searchTermParameter);
        }
    }
}
