//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronaFlow_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtasks
    {
        public long id { get; set; }
        public long task_id { get; set; }
        public string name { get; set; }
        public bool is_completed { get; set; }
        public int position { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual tasks tasks { get; set; }
    }
}
